### ISSUE TITLE
Other models for transfer learning

### ISSUE THREAD

**Issue by gregjauvion** [NVlabs/stylegan2-ada#38]
Hi,

I am training a GAN on images of buildings.
Until now, I used StyleGAN2 using transfer learning, starting from the model learnt on LSUN church dataset (and available on this repo https://github.com/NVlabs/stylegan2).
I would like to switch to StyleGAN2 with ADA because of the limited size of my dataset, but the LSUN church model available on StyleGAN2 repo is not compatible with StyleGAN2 with ADA.
Did anyone encounter the same issue ?

**Comment by JulianPinzaru** [comment]
@gregjauvion 
What do you mean by not compatible ? Is it showing you any errors ?
Did you try to pass it "--res=512" parameter to train.py command ? (if your resolution is 512 for example)

Although I didn't try to do any transfer learning from an older stylegan2 pkl file, I would suggest you to transfer learning from any pretrained model that matches your particular resolution. Transfer learning diminishes all the older weights anyways, so you won't benefit from "their buildings" too much, unless those same buildings are present in your dataset. I would say you can use any pkl of faces, cats or dogs to start transfer learning, and it will help you to achieve the base shapes and geometry in the very beginning of training instead of letting it doing backpropagation for it. 

P.S.
Maybe you can try

**Comment by gregjauvion** [comment]
Hi @JulianPinzaru and thanks a lot for your answer.
It was actually quite easy to fix: I've just passed "--cfg=stylegan2" to make it work, there are a few differences in the way models are built between stylegan2 and stylegan2-ada.

And thanks for the forked repo which includes a lot of features I was planning to implement myself :)
